### ISSUE TITLE
a small problem

### ISSUE THREAD

**Issue by WDS-DEEP** [IvanDrokin/torch-conv-kan#4]
The parameter optimizer LBFGS does not appear to be in the train folder.My English is not very good, thank you for the update.

**Comment by IvanDrokin** [comment]
@WDS-DEEP Hi there! Yes, I removed this file because of integration issues, I'll add LBFGS optimizer as an option later. If you faced a bug because of it - please, use the latest commit, everything should be fine, AdamW and Lion optimizers are available now. If you still encounter a bug, please feel free to open an issue again with all details that could help me to reproduce the issue
